'use client';
import { useMemo, useState } from 'react';

export type SearchableOption = { value: string; label: string };
function normalize(value: string) {
  return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
}
export function SearchableCombobox({ id, name, options, value, onChange, placeholder, searchPlaceholder = 'Escribe para buscar...', required = false, disabled = false }: { id: string; name: string; options: SearchableOption[]; value: string; onChange: (value: string) => void; placeholder: string; searchPlaceholder?: string; required?: boolean; disabled?: boolean }) {
  const [query, setQuery] = useState(''); const [open, setOpen] = useState(false);
  const selected = options.find((option) => option.value === value);
  const filtered = useMemo(() => { const term = normalize(query); return term ? options.filter((option) => normalize(option.label).includes(term)) : options; }, [options, query]);
  return <div className="relative"><input type="hidden" name={name} value={value} required={required} /><input id={id} disabled={disabled} role="combobox" aria-expanded={open} aria-controls={`${id}-options`} aria-autocomplete="list" value={open ? query : (selected?.label ?? '')} placeholder={selected ? undefined : placeholder} onFocus={() => { if (!disabled) setOpen(true); }} onChange={(event) => { if (value) onChange(''); setQuery(event.target.value); setOpen(true); }} onKeyDown={(event) => { if (event.key === 'Escape') { setQuery(''); setOpen(false); } }} onBlur={() => setTimeout(() => setOpen(false), 120)} className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 pr-10 disabled:cursor-not-allowed disabled:bg-slate-100" />{selected && !disabled ? <button type="button" aria-label={`Limpiar ${placeholder.toLowerCase()}`} onMouseDown={(event) => event.preventDefault()} onClick={() => { onChange(''); setQuery(''); setOpen(true); }} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-full px-1 text-lg text-slate-400 hover:bg-slate-100 hover:text-slate-700">×</button> : null}{open && !disabled ? <ul id={`${id}-options`} role="listbox" className="absolute z-20 mt-1 max-h-56 w-full overflow-auto rounded-xl border border-slate-200 bg-white p-1 shadow-lg">{filtered.length ? filtered.map((option) => <li key={option.value} role="option" aria-selected={option.value === value}><button type="button" onMouseDown={(event) => event.preventDefault()} onClick={() => { onChange(option.value); setQuery(''); setOpen(false); }} className="w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-sky-50">{option.label}</button></li>) : <li className="px-3 py-2 text-sm text-slate-500">No se encontraron coincidencias.</li>}</ul> : null}{!open && !selected ? <p className="mt-1 text-xs text-slate-500">{searchPlaceholder}</p> : null}</div>;
}
