create extension if not exists pgcrypto;

create type public.app_role as enum ('ADMIN', 'APODERADO', 'PORTERIA', 'DOCENTE', 'ESTUDIANTE');
create type public.authorization_type as enum ('PERMANENTE', 'TEMPORAL');
create type public.access_event_type as enum ('INGRESO', 'SALIDA');
create type public.exit_type as enum ('REGULAR', 'RETIRO_AUTORIZADO', 'SOLO');
create type public.validation_method as enum ('FACIAL', 'QR', 'PIN', 'MANUAL');
create type public.access_result as enum ('APROBADO', 'RECHAZADO');
create type public.block_type as enum ('ASIGNATURA', 'TALLER', 'DEPORTE', 'RECREO', 'ALMUERZO', 'ACTIVIDAD');
create type public.attendance_status as enum ('PRESENTE', 'AUSENTE', 'TARDANZA', 'SALIDA');

create table public.institutions (
  id bigint generated by default as identity primary key,
  name text not null,
  institution_type text,
  created_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  institution_id bigint references public.institutions(id) on delete set null,
  first_name text,
  last_name text,
  email text unique,
  role public.app_role not null default 'APODERADO',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.courses (
  id bigint generated by default as identity primary key,
  institution_id bigint not null references public.institutions(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table public.students (
  id bigint generated by default as identity primary key,
  institution_id bigint not null references public.institutions(id) on delete cascade,
  course_id bigint references public.courses(id) on delete set null,
  first_name text not null,
  last_name text not null,
  can_leave_alone boolean not null default false,
  is_in_institution boolean not null default false,
  link_code text not null unique default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.guardian_students (
  id bigint generated by default as identity primary key,
  guardian_profile_id uuid not null references public.profiles(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  relation_type text,
  created_at timestamptz not null default now(),
  unique (guardian_profile_id, student_id)
);

create table public.authorized_people (
  id bigint generated by default as identity primary key,
  institution_id bigint not null references public.institutions(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  document_identity text unique,
  phone text,
  kinship text,
  created_at timestamptz not null default now()
);

create table public.authorizations (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  authorized_person_id bigint not null references public.authorized_people(id) on delete cascade,
  guardian_profile_id uuid not null references public.profiles(id) on delete cascade,
  authorization_kind public.authorization_type not null default 'PERMANENTE',
  start_date date,
  end_date date,
  created_at timestamptz not null default now()
);

create table public.schedule_blocks (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 1 and 7),
  start_time time not null,
  end_time time not null,
  block_kind public.block_type not null,
  block_name text not null,
  location text,
  exit_allowed boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.attendance_blocks (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  schedule_block_id bigint not null references public.schedule_blocks(id) on delete cascade,
  attendance_date date not null default current_date,
  status public.attendance_status not null default 'AUSENTE',
  note text,
  created_at timestamptz not null default now(),
  unique (student_id, schedule_block_id, attendance_date)
);

create table public.access_events (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  authorized_person_id bigint references public.authorized_people(id) on delete set null,
  recorded_by_profile_id uuid references public.profiles(id) on delete set null,
  event_type public.access_event_type not null,
  exit_kind public.exit_type,
  validation_kind public.validation_method not null default 'MANUAL',
  result public.access_result not null default 'APROBADO',
  notes text,
  occurred_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, first_name, last_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_updated_at before update on public.profiles
for each row execute procedure public.touch_updated_at();

create trigger students_updated_at before update on public.students
for each row execute procedure public.touch_updated_at();

create or replace function public.apply_access_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  schedule_record record;
begin
  if new.result = 'APROBADO' then
    if new.event_type = 'INGRESO' then
      update public.students
      set is_in_institution = true
      where id = new.student_id;

      for schedule_record in
        select id
        from public.schedule_blocks
        where course_id = (select course_id from public.students where id = new.student_id)
          and day_of_week = extract(isodow from new.occurred_at)::smallint
      loop
        insert into public.attendance_blocks (student_id, schedule_block_id, attendance_date, status, note)
        values (new.student_id, schedule_record.id, new.occurred_at::date, 'PRESENTE', 'Marcado automaticamente por ingreso')
        on conflict (student_id, schedule_block_id, attendance_date)
        do update set status = 'PRESENTE', note = excluded.note;
      end loop;
    elsif new.event_type = 'SALIDA' then
      update public.students
      set is_in_institution = false
      where id = new.student_id;
    end if;
  end if;

  return new;
end;
$$;

create trigger access_events_after_insert
after insert on public.access_events
for each row execute procedure public.apply_access_event();

create or replace function public.current_user_role()
returns public.app_role
language sql
stable
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.current_user_institution_id()
returns bigint
language sql
stable
as $$
  select institution_id from public.profiles where id = auth.uid();
$$;

alter table public.profiles enable row level security;
alter table public.institutions enable row level security;
alter table public.courses enable row level security;
alter table public.students enable row level security;
alter table public.guardian_students enable row level security;
alter table public.authorized_people enable row level security;
alter table public.authorizations enable row level security;
alter table public.schedule_blocks enable row level security;
alter table public.attendance_blocks enable row level security;
alter table public.access_events enable row level security;

create policy "profiles can view themselves"
  on public.profiles for select
  using (auth.uid() = id);

create policy "profiles can update themselves"
  on public.profiles for update
  using (auth.uid() = id);

create policy "authenticated users can see institutions"
  on public.institutions for select
  to authenticated
  using (true);

create policy "authenticated users can see courses in their institution"
  on public.courses for select
  to authenticated
  using (institution_id = public.current_user_institution_id());

create policy "guardians can see own links"
  on public.guardian_students for select
  to authenticated
  using (guardian_profile_id = auth.uid());

create policy "guardians can create own links"
  on public.guardian_students for insert
  to authenticated
  with check (guardian_profile_id = auth.uid());

create policy "guardians can delete own links"
  on public.guardian_students for delete
  to authenticated
  using (guardian_profile_id = auth.uid());

create policy "institution staff can see all students"
  on public.students for select
  to authenticated
  using (
    institution_id = public.current_user_institution_id()
    and public.current_user_role() in ('ADMIN', 'PORTERIA', 'DOCENTE')
  );

create policy "guardians can see linked students"
  on public.students for select
  to authenticated
  using (
    exists (
      select 1
      from public.guardian_students gs
      where gs.student_id = students.id
        and gs.guardian_profile_id = auth.uid()
    )
  );

create policy "staff can update students in institution"
  on public.students for update
  to authenticated
  using (
    institution_id = public.current_user_institution_id()
    and public.current_user_role() in ('ADMIN', 'PORTERIA', 'DOCENTE')
  );

create policy "guardians can view schedule blocks from linked students"
  on public.schedule_blocks for select
  to authenticated
  using (
    exists (
      select 1
      from public.students s
      join public.guardian_students gs on gs.student_id = s.id
      where s.course_id = schedule_blocks.course_id
        and gs.guardian_profile_id = auth.uid()
    )
    or (
      public.current_user_role() in ('ADMIN', 'PORTERIA', 'DOCENTE')
      and exists (
        select 1
        from public.courses c
        where c.id = schedule_blocks.course_id
          and c.institution_id = public.current_user_institution_id()
      )
    )
  );

create policy "guardians can view linked attendance"
  on public.attendance_blocks for select
  to authenticated
  using (
    exists (
      select 1
      from public.guardian_students gs
      where gs.student_id = attendance_blocks.student_id
        and gs.guardian_profile_id = auth.uid()
    )
    or exists (
      select 1
      from public.students s
      where s.id = attendance_blocks.student_id
        and s.institution_id = public.current_user_institution_id()
        and public.current_user_role() in ('ADMIN', 'PORTERIA', 'DOCENTE')
    )
  );

create policy "staff can manage attendance"
  on public.attendance_blocks for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.students s
      where s.id = attendance_blocks.student_id
        and s.institution_id = public.current_user_institution_id()
        and public.current_user_role() in ('ADMIN', 'PORTERIA', 'DOCENTE')
    )
  );

create policy "staff can update attendance"
  on public.attendance_blocks for update
  to authenticated
  using (
    exists (
      select 1
      from public.students s
      where s.id = attendance_blocks.student_id
        and s.institution_id = public.current_user_institution_id()
        and public.current_user_role() in ('ADMIN', 'PORTERIA', 'DOCENTE')
    )
  );

create policy "guardians can view linked access events"
  on public.access_events for select
  to authenticated
  using (
    exists (
      select 1
      from public.guardian_students gs
      where gs.student_id = access_events.student_id
        and gs.guardian_profile_id = auth.uid()
    )
    or exists (
      select 1
      from public.students s
      where s.id = access_events.student_id
        and s.institution_id = public.current_user_institution_id()
        and public.current_user_role() in ('ADMIN', 'PORTERIA', 'DOCENTE')
    )
  );

create policy "staff can insert access events"
  on public.access_events for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.students s
      where s.id = access_events.student_id
        and s.institution_id = public.current_user_institution_id()
        and public.current_user_role() in ('ADMIN', 'PORTERIA', 'DOCENTE')
    )
  );

create policy "authenticated users can see authorized people in their institution"
  on public.authorized_people for select
  to authenticated
  using (institution_id = public.current_user_institution_id());

create policy "authenticated users can see authorizations of linked students or own institution"
  on public.authorizations for select
  to authenticated
  using (
    exists (
      select 1
      from public.guardian_students gs
      where gs.student_id = authorizations.student_id
        and gs.guardian_profile_id = auth.uid()
    )
    or exists (
      select 1
      from public.students s
      where s.id = authorizations.student_id
        and s.institution_id = public.current_user_institution_id()
        and public.current_user_role() in ('ADMIN', 'PORTERIA', 'DOCENTE')
    )
  );
