create table if not exists public.student_profiles (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete cascade,
  student_id bigint references public.students(id) on delete cascade,
  institution_id bigint references public.institutions(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.student_profiles
  add column if not exists profile_id uuid references public.profiles(id) on delete cascade,
  add column if not exists student_id bigint references public.students(id) on delete cascade,
  add column if not exists institution_id bigint references public.institutions(id) on delete cascade,
  add column if not exists created_at timestamptz not null default now();

update public.student_profiles sp
set institution_id = coalesce(p.institution_id, s.institution_id)
from public.profiles p
join public.students s on true
where p.id = sp.profile_id
  and s.id = sp.student_id
  and sp.institution_id is null;

do $$
begin
  if exists (
    select 1
    from public.student_profiles
    where profile_id is null
       or student_id is null
       or institution_id is null
  ) then
    raise exception 'student_profiles tiene filas incompletas. Completa profile_id, student_id e institution_id antes de aplicar NOT NULL.';
  end if;
end $$;

alter table public.student_profiles
  alter column profile_id set not null,
  alter column student_id set not null,
  alter column institution_id set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'student_profiles_profile_id_key'
      and conrelid = 'public.student_profiles'::regclass
  ) then
    alter table public.student_profiles
      add constraint student_profiles_profile_id_key unique (profile_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'student_profiles_student_id_key'
      and conrelid = 'public.student_profiles'::regclass
  ) then
    alter table public.student_profiles
      add constraint student_profiles_student_id_key unique (student_id);
  end if;
end $$;

create index if not exists idx_student_profiles_profile_id
on public.student_profiles(profile_id);

create index if not exists idx_student_profiles_student_id
on public.student_profiles(student_id);

create index if not exists idx_student_profiles_institution_id
on public.student_profiles(institution_id);

alter table public.student_profiles enable row level security;

drop policy if exists "students can view own student record"
  on public.students;

create policy "students can view own student record"
  on public.students for select
  to authenticated
  using (
    exists (
      select 1
      from public.student_profiles sp
      where sp.student_id = students.id
        and sp.profile_id = auth.uid()
        and sp.institution_id = students.institution_id
    )
  );

drop policy if exists "students can view own student profile link"
  on public.student_profiles;

create policy "students can view own student profile link"
  on public.student_profiles for select
  to authenticated
  using (profile_id = auth.uid());

drop policy if exists "staff can view student profile links in institution"
  on public.student_profiles;

create policy "staff can view student profile links in institution"
  on public.student_profiles for select
  to authenticated
  using (
    institution_id = public.current_user_institution_id()
    and public.current_user_role() in ('ADMIN', 'PORTERIA')
  );

drop policy if exists "admins can manage student profile links in institution"
  on public.student_profiles;

create policy "admins can manage student profile links in institution"
  on public.student_profiles for all
  to authenticated
  using (
    institution_id = public.current_user_institution_id()
    and public.current_user_role() = 'ADMIN'
  )
  with check (
    institution_id = public.current_user_institution_id()
    and public.current_user_role() = 'ADMIN'
  );

drop policy if exists "students can read own qr credentials"
  on public.student_qr_credentials;

create policy "students can read own qr credentials"
  on public.student_qr_credentials for select
  to authenticated
  using (
    created_by = auth.uid()
    and exists (
      select 1
      from public.student_profiles sp
      where sp.student_id = student_qr_credentials.student_id
        and sp.profile_id = auth.uid()
        and sp.institution_id = student_qr_credentials.institution_id
    )
  );

drop policy if exists "students can create own qr credentials"
  on public.student_qr_credentials;

create policy "students can create own qr credentials"
  on public.student_qr_credentials for insert
  to authenticated
  with check (
    created_by = auth.uid()
    and exists (
      select 1
      from public.student_profiles sp
      where sp.student_id = student_qr_credentials.student_id
        and sp.profile_id = auth.uid()
        and sp.institution_id = student_qr_credentials.institution_id
    )
  );

insert into public.student_profiles (
  profile_id,
  student_id,
  institution_id
)
select
  p.id,
  s.id,
  coalesce(p.institution_id, s.institution_id)
from public.profiles p
join public.students s
  on s.institution_id = p.institution_id
 and lower(trim(s.first_name)) = lower(trim(p.first_name))
 and lower(trim(s.last_name)) = lower(trim(p.last_name))
where p.email = 'alan.estudiante@validgate.app'
  and p.role = 'ESTUDIANTE'
  and p.institution_id is not null
on conflict do nothing;

insert into public.student_profiles (
  profile_id,
  student_id,
  institution_id
)
select
  p.id,
  s.id,
  coalesce(p.institution_id, s.institution_id)
from public.profiles p
join public.students s
  on s.institution_id = p.institution_id
 and s.link_code = 'VG-ALAN-BETTANCOURT'
where p.email = 'alan.estudiante@validgate.app'
  and p.role = 'ESTUDIANTE'
  and p.institution_id is not null
on conflict do nothing;

comment on table public.student_profiles is
  'Relaciona perfiles autenticados con registros students para usuarios con rol ESTUDIANTE.';
